### ISSUE TITLE
Provided example doesn't work

### ISSUE THREAD

**Issue by Ashish0804** [anuragagrawaal/pyPortfolioAnalysis#3]
Provided example seems to have few errors like

- Not importing pandas.
- Not explicitly mentioning the package pyPortfolioAnalysis when calling functions. 
- Not defining R

Solutions

-  import pandas as pd
- from pyPortfolioAnalysis import *
- i don't know how R should be defined and i recommend using a better name, for example returnsDF

**Comment by anuragagrawaal** [comment]
Thanks,
I have updated the example.
